name: RestpSign
main: com.ayou.restpsign.RestpSign
version: 0.0.1
author: Ayou
depend: [Residence]
softdepend: [Vault]
commands:
  restp:
    description: Main command
    usage: /restp help
permissions:
  restpsign.admin:
    description: Admin permission
    default: op
  restpsign.reload:
    description: reloadcmd permission
    default: op
  restpsign.create:
    description: Create sign permission
    default: true
  restpsign.help:
    description: helpcmd permission
    default: true
  restpsign.edit:
    description: editcmd sign permission
    default: true
  restpsign.subzones:
    description: subzonescmd permission
    default: true
  restpsign.bypasscooldown:
    description: bypasscooldown permission
    default: op
  restpsign.bypassmoney:
    description: bypassmoney permission
    default: op